---
title: "class11"
author: "Katie Mostoller A17259578"
format: pdf
---

# Section 1. proption of G/G in a population

Read the csv file
```{r}
mxl <- read.csv("373531-SampleGenotypes-Homo_sapiens_Variation_Sample_rs8067378.csv")
head(mxl)
```
```{r}
table(mxl$Genotype..forward.strand.)
```

```{r}
table(mxl$Genotype..forward.strand.)/nrow(mxl) *100
```

## Section 4: population analysis


```{r}
expr <- read.table("rs8067378_ENSG00000172057.6.txt")
head(expr)
```


```{r}
nrow(expr)
```


>Q13. Read this file into R and determine the sample size for each genotype and their
corresponding median expression levels for each of these genotypes

```{r}
table(expr$geno)
```
```{r}
library(dplyr)

summary_stats <- expr %>%
  group_by(geno) %>%
  summarise(
    Sample_Size = n(),
    Median_Expression = median(exp))

summary_stats
```



```{r}
library(ggplot2)
```
 
 >Q14. Make a boxplot!
 
```{r}
ggplot(expr) + aes(x = geno, y = exp, fill = geno) + geom_boxplot(notch = TRUE) + xlab("Genotype") + ylab("Expression")
```
 
 